### ISSUE TITLE
CRUD 1차 주제 회의

### ISSUE THREAD

**Issue by healim01** [healimfx/OSS_CRUDTeam14#2]
CRUD 1차 주제 정하기

**Comment by 22000072-kimminki** [comment]
1. 게임 임포스터에서 착안한 환경지킴 CRUD
 - 회원 추가
 - 회원 관리하여 팀 관리
 - 미션을 추가
 - 팀별로 포인트 추가

**Comment by healim01** [comment]
2. 한동대 학생 리스트
 
- 학생 명단
- 학생 파일 저장/ 읽기
- 명단 검색
- 새섬/새새 정하기

**Comment by healim01** [comment]
2번으로 하겠습니다!!
