### ISSUE TITLE
CRUD 함수 결정 회의

### ISSUE THREAD

**Issue by healim01** [healimfx/OSS_CRUDTeam14#3]
CRUD 함수 결정 회의

**Comment by healim01** [comment]
구조체 정보

학생 정보
- 이름
- 학번
- 학년
- 전공
- 기숙사

**Comment by 22000072-kimminki** [comment]
학생 정보 추가 
학생 정보 읽기
학생 정보 업데이트
학생 정보 삭제

-> 이것도 추가해보겠습니다

**Comment by healim01** [comment]
학생 정보 파일 읽어오기 
학생 정보 파일 저장하기 

-> 데이타 파일 부분도 추가했습니다!

**Comment by 22000072-kimminki** [comment]
팀 정하기

팀 정하기 

학생 이름으로 검색
학생 학번으로 검색 

-> 랜덤 및 검색 기능 추가하겠습니다.

**Comment by healim01** [comment]
전공별 검색
학년별 검색

-> 해당 부분도 검색 기능에 추가하면 좋을거 같습니다!

**Comment by healim01** [comment]
한동대 학생 리스트

학생 정보
- 이름
- 학번
- 학년
- 전공
- 기숙사 

학생 정보 추가 
학생 정보 읽기
학생 정보 업데이트
학생 정보 삭제

학생 정보 파일 읽어오기 
학생 정보 파일 저장하기 

팀 정하기 

학생 이름으로 검색
학생 학번으로 검색 
전공별 검색
학년별 검색

-> 최종 함수 기능으로 결정하겠습니다!!
